---

# Users
users:
  - { name: "antoine", sshkey: "antoine" } 
  - { name: "sebastien", sshkey: "sebastien" } 
<<<<<<< HEAD
tmp_password: "6p2lpqm6l0x8xIPA"
=======
tmp_password: "HGH88dr_ogULuoqu"
>>>>>>> 42b4c34855e6e669f852e05e186ada9419f45fe1
