- name: reload_daemon_and_restart_node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Redis_Restart
  service: 
    name: redis-server 
    state: restarted 
    enabled: yes
  